### ISSUE TITLE
Support ESRI File Geodatabase

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-postgis-conversion#10]
Estimated duration: ~?d

### To reproduce
1. Check out a branch of this repo with dockerized excerpt extraction, e.g.

        git clone -b feature/make_main-bootstrap.sh_suitable_for_docker \
                     git@github.com:geometalab/osmaxx-data-wrangling.git
2. Change into the repo's root dir

        cd osmaxx-data-wrangling
3. Build the containers

        docker-compose build
4. Start the database service

        docker-compose start
5. Run the boostrap script

        docker-compose run script sh main-bootstrap.sh
    **or** simply

        docker-compose up
6. Try to extract Rapperswil as ESRI File Geodatabase

        docker-compose run excerpt python excerpt.py 8.775449276  47.1892350573 \
                                                     8.8901920319 47.2413633153 -f fgdb

#### Expected

* Output similar to

        Calculating Statistics...
        Statistics Done!!
        starting osmaxx_excerpt_2015-08-10_133217
        osmaxx_excerpt_2015-08-10_133217 have been Generated.. Zipping files
          adding: data/osmaxx_excerpt_2015-08-10_133217.dgb (deflated ????%)
          adding: README.txt (deflated 38%)
          adding: LICENCE.txt (deflated 19%)
          adding: METADATA.txt (deflated 51%)
          adding: doc/ (stored 0%)
          adding: doc/Osmaxx_Data_Model_v3_23-05-2015.odt (deflated 3%)
          adding: doc/Osmaxx_Data_Model_v3_23-05-2015.pdf (deflated 13%)
          adding: osmaxx_excerpt_2015-08-10_133217_STATISTICS.csv (deflated 87%)
        Zip done! Exiting....
* a new zip file in `results`

#### Observed
* Output

        Calculating Statistics...
        Statistics Done!!
        starting osmaxx_excerpt_2015-08-10_143827
        Unable to find driver `FileGDB'.
        The following drivers are available:
          -> `ESRI Shapefile'
          -> `MapInfo File'
          -> `UK .NTF'
          -> `SDTS'
          -> `TIGER'
          -> `S57'
          -> `DGN'
          -> `VRT'
          -> `REC'
          -> `Memory'
          -> `BNA'
          -> `CSV'
          -> `NAS'
          -> `GML'
          -> `GPX'
          -> `LIBKML'
          -> `KML'
          -> `GeoJSON'
          -> `Interlis 1'
          -> `Interlis 2'
          -> `GMT'
          -> `GPKG'
          -> `SQLite'
          -> `DODS'
          -> `ODBC'
          -> `WAsP'
          -> `PGeo'
          -> `MSSQLSpatial'
          -> `OGDI'
          -> `PostgreSQL'
          -> `MySQL'
          -> `PCIDSK'
          -> `OpenFileGDB'
          -> `XPlane'
          -> `AVCBin'
          -> `AVCE00'
          -> `DXF'
          -> `Geoconcept'
          -> `GeoRSS'
          -> `GPSTrackMaker'
          -> `VFK'
          -> `PGDump'
          -> `OSM'
          -> `GPSBabel'
          -> `SUA'
          -> `OpenAir'
          -> `PDS'
          -> `WFS'
          -> `HTF'
          -> `AeronavFAA'
          -> `Geomedia'
          -> `EDIGEO'
          -> `GFT'
          -> `GME'
          -> `SVG'
          -> `CouchDB'
          -> `Idrisi'
          -> `ARCGEN'
          -> `SEGUKOOA'
          -> `SEGY'
          -> `XLS'
          -> `ODS'
          -> `XLSX'
          -> `ElasticSearch'
          -> `PDF'
          -> `Walk'
          -> `CartoDB'
          -> `SXF'
        Traceback (most recent call last):
          File "excerpt.py", line 84, in <module>
            call_fgdb([str(min_xy[0]), str(min_xy[1]), str(max_xy[0]), str(max_xy[1])], name)
          File "excerpt.py", line 29, in call_fgdb
            subprocess.check_call(gdbcmd)
          File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '('sh', './extract/extract_fgdb.sh', '976878.544887', '5973016.93556', '989651.650046', '5981560.08087', 'osmaxx_excerpt_2015-08-10_143827')' returned non-zero exit status 1

* no new zip file in `results/`

**Comment by das-g** [comment]
Requires a [GDAL driver](http://www.gdal.org/drv_filegdb.html) relying on proprietary libraries.
