### ISSUE TITLE
ESRI Shapefile export broken "Unable to open datasource"

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-postgis-conversion#18]
### To reproduce:
0. Build the containers

        docker-compose build
1. Initialize database

        docker-compose run bootstrap /bin/bash -c \
          'sleep 10 && sh main-bootstrap.sh 8.775449276 47.1892350573 8.8901920319 47.2413633153'
2. Try to extract an ESRI Shapefile

        docker-compose run extract python excerpt.py 8.775449276 47.1892350573 8.8901920319 47.2413633153 -f shp

#### Expected:
A zip file is produced in `results/`

#### Observed:

    Calculating Statistics...
    Statistics Done!!
    starting osmaxx_excerpt_2015-08-25_081552
    FAILURE:
    Unable to open datasource `/home/excerpt/data/osmaxx_excerpt_2015-08-25_081552.shp' with the following drivers.
      -> ESRI Shapefile
      -> MapInfo File
      -> UK .NTF
      -> SDTS
      -> TIGER
      -> S57
      -> DGN
      -> VRT
      -> REC
      -> Memory
      -> BNA
      -> CSV
      -> NAS
      -> GML
      -> GPX
      -> LIBKML
      -> KML
      -> GeoJSON
      -> Interlis 1
      -> Interlis 2
      -> GMT
      -> GPKG
      -> SQLite
      -> DODS
      -> ODBC
      -> WAsP
      -> PGeo
      -> MSSQLSpatial
      -> OGDI
      -> PostgreSQL
      -> MySQL
      -> PCIDSK
      -> OpenFileGDB
      -> XPlane
      -> AVCBin
      -> AVCE00
      -> DXF
      -> Geoconcept
      -> GeoRSS
      -> GPSTrackMaker
      -> VFK
      -> PGDump
      -> OSM
      -> GPSBabel
      -> SUA
      -> OpenAir
      -> PDS
      -> WFS
      -> HTF
      -> AeronavFAA
      -> Geomedia
      -> EDIGEO
      -> GFT
      -> GME
      -> SVG
      -> CouchDB
      -> Idrisi
      -> ARCGEN
      -> SEGUKOOA
      -> SEGY
      -> XLS
      -> ODS
      -> XLSX
      -> ElasticSearch
      -> PDF
      -> Walk
      -> CartoDB
      -> SXF
    Traceback (most recent call last):
      File "excerpt.py", line 49, in <module>
        export_from_db_to_format([str(min_xy[0]), str(min_xy[1]), str(max_xy[0]), str(max_xy[1])], name, args.format)
      File "excerpt.py", line 32, in export_from_db_to_format
        subprocess.check_call(dbcmd)
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '('sh', './extract/extract_format.sh', '976878.544887', '5973016.93556', '989651.650046', '5981560.08087', 'osmaxx_excerpt_2015-08-25_081552', 'shp')' returned non-zero exit status 1

**Comment by das-g** [comment]
The space in "ESRI Shapefile"  at https://github.com/geometalab/osmaxx-postgis-conversion/commit/b3aec9ddddcdcf84d482799d27ac820889bc492e#diff-c64cd4a78ad6de6c750206d6040824bfR23 needs to be protected when `$TYPE` is used at https://github.com/geometalab/osmaxx-postgis-conversion/commit/b3aec9ddddcdcf84d482799d27ac820889bc492e#diff-c64cd4a78ad6de6c750206d6040824bfR44
